### ISSUE TITLE
How can I fix this issye?

### ISSUE THREAD

**Issue by alex198555** [anniedotexe/Instagram-Like-Comment-Bot#10]
The script doesn't click the picture after found the tag: 

C:\Users\aorek\Desktop\Python Bots\Instagram-Like-Comment-Bot-master\Instagram-Like-Comment-Bot-master> python insta-bot.py
INFO [04/23/2022 09:44:37 PM] Logged in to amca_st
INFO [04/23/2022 09:44:41 PM] Exploring #urbanandstreet
Traceback (most recent call last):
  File "C:\Users\aorek\Desktop\Python Bots\Instagram-Like-Comment-Bot-master\Instagram-Like-Comment-Bot-master\insta-bot.py", line 75, in <module>
    first_thumbnail = browser.find_element_by_xpath(
  File "C:\Users\aorek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\aorek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\aorek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\aorek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/section/main/article/div[1]/div/div/div[1]/div[1]/a/div/div[2]"}
  (Session info: chrome=100.0.4896.127)

Any solution how to fix it?

**Comment by anniedotexe** [comment]
Has been updated
