### ISSUE TITLE
Issue on start

### ISSUE THREAD

**Issue by anthonyarutyunov** [anniedotexe/Instagram-Like-Comment-Bot#11]
The script will open a window in Chrome, but then proceed to close it and give me this error:

INFO [01/28/2023 08:54:39 PM] Logged in to bobjefferson141
Traceback (most recent call last):
  File "C:\Users\antho\OneDrive\Documents\Visual Studio 2022\Workspaces\PIP\Instagram-Like-Comment-Bot\insta-bot.py", line 69, in <module>
    browser.get(
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id

**Comment by anthonyarutyunov** [comment]
I fixed myself: The chrome driver is detected by Instagram so I modified the detected parameters with a hex editor and everything works now.
